version: '3'

services:
  ldap:
    image: bersace/openldap:latest
    environment:
      # To debug slapd configuration:
      # LDAP_LOG_LEVEL: 33768
      LDAP_DOMAIN: ldap.ldap2pg.docker
      LDAP_ADMIN_PASSWORD: integral
      LDAP_ORGANISATION: ldap2pg
    volumes:
    - ./test/fixtures/openldap-config.ldif:/docker-entrypoint-init.d/90-config.ldif
    - ./test/fixtures/openldap-data.ldif:/docker-entrypoint-init.d/95-data.ldif
    hostname: ldap
    domainname: ldap2pg.docker
    labels:
      com.dnsdock.alias: ldap.ldap2pg.docker

  postgres:
    image: postgres:${PGVERSION-15}-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
    - ./test/fixtures/postgres.sh:/docker-entrypoint-initdb.d/fixture.sh
    labels:
      com.dnsdock.alias: postgres.ldap2pg.docker
    command: [
      postgres,
      -c, log_statement=all,
      -c, log_connections=on,
      -c, "log_line_prefix=%m [%p]: [%l-1] app=%a,db=%d,client=%h,user=%u ",
      -c, cluster_name=ldap2pg-dev,
    ]
