version: '2'

services:
  secondaryldap:
    image: bersace/openldap:latest
    environment:
      # To debug slapd configuration:
      # LDAP_LOGLEVEL: 33768
      LDAP_DOMAIN: ldap.ldap2pg.docker
      LDAP_ADMIN_PASSWORD: integral
      LDAP_ORGANISATION: ldap2pg
    volumes:
    - ./test/fixtures/openldap-config.ldif:/container/service/slapd/assets/config/bootstrap/ldif/90-config.ldif
    - ./test/fixtures/openldap-data.ldif:/container/service/slapd/assets/config/bootstrap/ldif/95-data.ldif
    hostname: secondary
    domainname: ldap.ldap2pg.docker
    labels:
      com.dnsdock.alias: secondary.ldap.ldap2pg.docker
