version: 2.1

workflows:
  version: 2
  default:
    jobs:
    - build:
        name: "stage0-build"
    - lint:
        name: "stage0-lint"
    - func:
        name: "stage1-func-rockylinux8-pg15"
        dist: rockylinux8
        requires: [stage0-build]
        pgversion: "15"
    - func:
        name: "stage1-func-centos7-pg12"
        dist: centos7
        requires: [stage0-build]
        pgversion: "12"
    - func:
        name: "stage1-func-centos6-pg9.5"
        dist: centos6
        requires: [stage0-build]
        pgversion: "9.5"
    - release:
        name: stage2-release
        # Send secrets to this jobs from temboard CircleCI context.
        context: ldap2pg
        filters:
          tags:
            only: '/v.+/'
          # Skip on branches!
          branches:
            ignore: '/.*/'


jobs:
  build:
    working_directory: &workspace /workspace
    docker:
    - image: goreleaser/goreleaser:v1.24.0
    steps:
    - checkout
    - restore_cache:
        keys: [go-build]
    - run:
        name: Build ldap2pg binary
        command: |
          goreleaser build --clean --snapshot --single-target
    - run:
        name: Smoke test
        command: dist/ldap2pg_linux_amd64_v1/ldap2pg --version
    - run:
        name: Unit Test
        command: |
          go test -v ./...
    - save_cache:
        key: go-build-{{ epoch }}
        paths:
        - /go/pkg/mod
        - /root/.cache/go-build
    - store_artifacts:
        path: /workspace/dist/
    - persist_to_workspace:
        root: .
        paths: [dist/]

  lint:
    working_directory: *workspace
    docker:
    - image: golangci/golangci-lint:v1.56.2
    steps:
    - checkout
    - restore_cache:
        keys: [ldap2pg-go-lint]
    - run:
        name: Lint
        command: |
          golangci-lint run
    - save_cache:
        key: go-lint-{{ epoch }}
        paths:
        - /root/.cache/golangci-lint
        - /root/.cache/go-build
        - /go/pkg/mod

  func:
    parameters:
      dist:
        description: "Distribution."
        type: string
      pgversion:
        description: "Major dotted version of PostgreSQL."
        type: string
    docker:
      - image: dalibo/buildpack-python:<< parameters.dist >>
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          PGPASSWORD: communication
          LDAPURI: ldap://ldap.ldap2pg.docker
          LDAPBINDDN: cn=admin,dc=ldap,dc=ldap2pg,dc=docker
          LDAPPASSWORD: communication
      - image: bersace/openldap@sha256:b03ac7f2d85831b93af53c1ac963c17170a4216a4307cf8865142fb6495aee21
        environment:
          LDAP_DOMAIN: ldap.ldap2pg.docker
          LDAP_ADMIN_PASSWORD: communication
          LDAP_ORGANISATION: ldap
      - image: postgres:<< parameters.pgversion >>-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: communication
    working_directory: *workspace
    steps:
    - checkout
    - attach_workspace:
        at: *workspace
    - restore_cache:
        keys: [ldap2pg-go-func]
    - run:
        name: Exécuting Functionnal Tests
        command: |
          echo 127.0.1.1 ldap.ldap2pg.docker >> /etc/hosts
          test/entrypoint.sh
    - save_cache:
        key: ldap2pg-go-func-{{ epoch }}
        paths:
        - /root/.cache/pip

  pkg:
    parameters:
      format:
        description: "nFPM packager"
        type: string
    docker: [{image: "dalibo/buildpack-pkg@sha256:5619b00328c5bd193412014b77295776f831cfa40f9feb37accc8f79b59b6de4"}]  # bullseye
    working_directory: *workspace
    steps:
    - checkout
    - attach_workspace:
        at: *workspace
    - run:
        name: nFPM
        command: |
          nfpm --version
          nfpm package --packager << parameters.format >> --target dist/
    - persist_to_workspace:
        root: *workspace
        paths: ["dist/*.deb", "dist/*.rpm"]

  release:
    # Configure secrets of this job in ldap2pg CircleCI context.
    docker: [{image: goreleaser/goreleaser:v1.19.2}]
    working_directory: *workspace
    steps:
    - checkout
    - restore_cache:
        keys: [go-build]
    - run:
        name: GoReleaser
        command: goreleaser release --clean
