#!/bin/bash
# Provision a Samba AD DC: realm BRIDOULOU.FR, admin password 1Ntegral,
# strong auth required (reproduces "SASL:[GSSAPI]: Sign or Seal are required").
set -eux

export DEBIAN_FRONTEND=noninteractive
export LANG=C.UTF-8 LC_ALL=C.UTF-8

LDAP_IP=192.168.56.10

# Kerberos needs a stable FQDN. Drop the 127.0.x.x alias Vagrant adds for the
# hostname so that ldap.bridoulou.fr resolves to the private network IP.
sed -i '/127\.0\.1\.1/d' /etc/hosts
grep -q 'ldap.bridoulou.fr' /etc/hosts || echo "$LDAP_IP ldap.bridoulou.fr ldap" >> /etc/hosts

echo "krb5-config krb5-config/default_realm string BRIDOULOU.FR" | debconf-set-selections

apt-get update
apt-get install -y samba winbind krb5-user smbclient ldap-utils libsasl2-modules-gssapi-mit dnsutils acl attr

systemctl disable --now smbd nmbd winbind 2>/dev/null || true

if [ ! -f /var/lib/samba/private/sam.ldb.provisioned ] ; then
	rm -f /etc/samba/smb.conf
	samba-tool domain provision \
		--realm=BRIDOULOU.FR \
		--domain=BRIDOULOU \
		--server-role=dc \
		--dns-backend=NONE \
		--host-name=ldap \
		--adminpass='1Ntegral' \
		--option='ldap server require strong auth = yes'
	touch /var/lib/samba/private/sam.ldb.provisioned
fi

# Use the Kerberos config generated by the provision (pin the KDC explicitly:
# there is no DNS backend, so SRV records are not available).
cat > /etc/krb5.conf <<'EOF'
[libdefaults]
	default_realm = BRIDOULOU.FR
	dns_lookup_realm = false
	dns_lookup_kdc = false
	rdns = false
	dns_canonicalize_hostname = false

[realms]
	BRIDOULOU.FR = {
		kdc = ldap.bridoulou.fr
		admin_server = ldap.bridoulou.fr
	}

[domain_realm]
	.bridoulou.fr = BRIDOULOU.FR
	bridoulou.fr = BRIDOULOU.FR
EOF

systemctl unmask samba-ad-dc
systemctl enable samba-ad-dc
systemctl restart samba-ad-dc

# Wait for the LDAP port.
for i in $(seq 1 60) ; do
	if ss -ltn | grep -q ':389 ' ; then break ; fi
	sleep 2
done
ss -ltn | grep ':389 '

samba-tool domain passwordsettings set --complexity=off --min-pwd-length=0 || true

# Load the same fixtures as docker-compose, plus LDIF-folding edge cases.
sed -i 's/\r$//' /tmp/fixtures/*.sh
if [ ! -f /var/lib/samba/private/fixtures.loaded ] ; then
	bash /tmp/fixtures/nominal.sh
	bash /tmp/fixtures/extra.sh
	bash /tmp/fixtures/fold.sh
	touch /var/lib/samba/private/fixtures.loaded
fi

# Smoke test: GSSAPI bind from the DC itself.
echo '1Ntegral' | kinit administrator@BRIDOULOU.FR
ldapsearch -Y GSSAPI -H ldap://ldap.bridoulou.fr -b cn=users,dc=bridoulou,dc=fr -LLL '(cn=readers)' cn member
kdestroy

echo "Samba AD DC provisioned."
